services:
  web:
    build:
      context: .
    command: ["./wait-for-it.sh", "db:3306", "--timeout=30", "--", "flask", "run", "--host=0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env

  db:
    image: mysql:8.4.0
    env_file:
      - .env