version: "3.3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Onelookdarkroom!
      DB_PASSWORD: Onelookdarkroom!
      DB_NAME: Chacharitas_final
      DB_USERNAME: Phantasos

  app:
    build: .
    depends_on:
      - mssql
    environment:
      DB_HOST: mssql
      DB_NAME: Chacharias_final
      DB_USERNAME: Phantasos
      DB_PASSWORD: Onelookdarkroom!